"""Build kernel.py: embeds the showcase training/export code so the private repo needn't be cloned.

Run from the repo root: python kaggle/deployable-transformer/build.py
Then push: kaggle kernels push -p kaggle/deployable-transformer
"""

import base64
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
FILES = [
    "backend/__init__.py",
    "backend/app/__init__.py",
    "backend/app/text.py",
    "backend/app/predictors.py",  # export_cpu.py reloads the int8 model through it
    "backend/inference.py",
    "scripts/__init__.py",
    "scripts/train_transformer.py",
    "scripts/export_cpu.py",
]
BASE = "FacebookAI/xlm-roberta-large"

blobs = {f: base64.b64encode((ROOT / f).read_bytes()).decode() if (ROOT / f).exists() else "" for f in FILES}
kernel = f'''# Deployable showcase transformer: XLM-R-large, 3 epochs, LR 1e-5 (2e-5 collapsed in v5), 256 tokens,
# duplicate-grouped 20% holdout, then int8 dynamic quantization gated on macro-F1 drop < 0.005.
# Generated by kaggle/deployable-transformer/build.py; do not edit by hand.
import base64, os, shutil, subprocess, sys
from pathlib import Path

APP = Path("/kaggle/working/app")
for rel, blob in {blobs!r}.items():
    path = APP / rel
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(base64.b64decode(blob))

# Match backend/requirements-transformer.txt (the Kaggle image ships transformers 5).
subprocess.run([sys.executable, "-m", "pip", "install", "-q", "transformers>=4.48,<5", "accelerate>=1.2,<2"], check=True)
# The competition mount path varies between Kaggle images, so search for it.
DATA = str(next(p for p in Path("/kaggle/input").rglob("train.csv") if "herwill" in str(p).lower()))
print("train:", DATA, flush=True)
OUT = Path("/kaggle/working/transformer")
# One T4: DataParallel over two T4s ran out of memory gathering gradients (v3, batch 16).
ENV = {{**os.environ, "CUDA_VISIBLE_DEVICES": "0", "PYTORCH_CUDA_ALLOC_CONF": "expandable_segments:True"}}
def run(*args):
    print("+", " ".join(args), flush=True)
    subprocess.run([sys.executable, *args], cwd=APP, env=ENV, check=True)

run("scripts/train_transformer.py", "--train", DATA, "--base", "{BASE}",
    "--download-base", "--output", str(OUT), "--epochs", "3", "--batch-size", "8", "--accumulation", "2",
    "--lr", "1e-5", "--warmup", "0.1")
shutil.rmtree(OUT / "checkpoints", ignore_errors=True)
run("scripts/export_cpu.py", "--model", str(OUT), "--validation", str(OUT / "heldout.csv"),
    "--output", "/kaggle/working/transformer-int8")
# heldout.csv holds competition text: keep it out of the downloadable output.
(OUT / "heldout.csv").unlink(missing_ok=True)
shutil.rmtree(APP, ignore_errors=True)
'''
(Path(__file__).parent / "kernel.py").write_text(kernel, encoding="utf-8")
print("wrote kernel.py")
