"""Build the two V6 kernels (stage 1 train on GPU, stage 2 int8 export on CPU); stage 3 is
scripts/fetch_transformer.py on your machine. Splitting means an export failure never costs a retrain,
and the CPU stage doesn't hold a GPU slot.

Run from the repo root:  python kaggle/deployable-transformer-v6/build.py
Push stage 1:            kaggle kernels push -p kaggle/deployable-transformer-v6/train
Push stage 2 only after stage 1 is COMPLETE:
                         kaggle kernels push -p kaggle/deployable-transformer-v6/export
"""

import base64
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
OWNER = "nasreenakhter229"
TRAIN_SLUG = "herwill-showcase-xlmr-large-train"
EXPORT_SLUG = "herwill-showcase-xlmr-large-export"
FILES = [
    "backend/__init__.py",
    "backend/app/__init__.py",
    "backend/app/text.py",
    "backend/app/predictors.py",  # export_cpu.py reloads the int8 model through it
    "backend/inference.py",
    "scripts/train_transformer.py",
    "scripts/export_cpu.py",
]

HEADER = '''import base64, os, shutil, subprocess, sys
from pathlib import Path

APP = Path("/kaggle/working/app")
for rel, blob in {blobs!r}.items():
    path = APP / rel
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(base64.b64decode(blob))
(APP / "scripts/__init__.py").touch()

# Match backend/requirements-transformer.txt (the Kaggle image ships transformers 5).
subprocess.run([sys.executable, "-m", "pip", "install", "-q", "transformers>=4.48,<5", "accelerate>=1.2,<2"], check=True)

ENV = {{**os.environ, "CUDA_VISIBLE_DEVICES": "0", "PYTORCH_CUDA_ALLOC_CONF": "expandable_segments:True"}}
def run(*args):
    print("+", " ".join(args), flush=True)
    subprocess.run([sys.executable, *args], cwd=APP, env=ENV, check=True)
'''

TRAIN = '''# V6 stage 1/3 (GPU): fine-tune XLM-R-large for the showcase Live Demo.
# 3 epochs, LR 1e-5 (2e-5 collapsed in V5), warmup 10%, 2 T4s via DDP (batch 8 each; falls back to one T4,
# batch 8 x 2 accumulation, if DDP crashes), 256 tokens,
# duplicate-grouped 20% holdout. Stops at once if a held-out eval falls below macro F1 0.35 (collapse).
# Generated by kaggle/deployable-transformer-v6/build.py; do not edit by hand.
''' + HEADER + '''
# The competition mount path varies between Kaggle images, so search for it.
DATA = str(next(p for p in Path("/kaggle/input").rglob("train.csv") if "herwill" in str(p).lower()))
print("train:", DATA, flush=True)
OUT = Path("/kaggle/working/transformer")
COMMON = ["scripts/train_transformer.py", "--train", DATA, "--base", "FacebookAI/xlm-roberta-large",
          "--download-base", "--output", str(OUT), "--epochs", "3", "--batch-size", "8",
          "--lr", "1e-5", "--warmup", "0.1", "--abort-below", "0.35"]
try:
    # Both T4s with DistributedDataParallel (one process per GPU, batch 8 each = effective 16).
    print("+ torchrun 2 GPUs", flush=True)
    subprocess.run([sys.executable, "-m", "torch.distributed.run", "--nproc_per_node=2", *COMMON,
                    "--accumulation", "1"], cwd=APP, env={{**os.environ, "PYTORCH_CUDA_ALLOC_CONF": "expandable_segments:True"}}, check=True)
except subprocess.CalledProcessError:
    if (OUT / "COLLAPSED").exists():
        raise SystemExit("Collapsed (held-out macro F1 below 0.35); not retrying")
    # Any other DDP failure: fall back to the proven single-T4 recipe (batch 8 x 2 accumulation).
    print("DDP failed; retrying on one GPU", flush=True)
    shutil.rmtree(OUT, ignore_errors=True)
    run(*COMMON, "--accumulation", "2")
shutil.rmtree(OUT / "checkpoints", ignore_errors=True)
shutil.rmtree(APP, ignore_errors=True)
# OUT keeps heldout.csv for stage 2; this kernel is private and the fetch step never downloads it.
'''

EXPORT = '''# V6 stage 2/3 (CPU): int8 dynamic quantization of the stage-1 model, gated on a macro-F1 drop < 0.005
# over the full held-out split (batched), plus a reload check through the app's own predictor.
# Generated by kaggle/deployable-transformer-v6/build.py; do not edit by hand.
''' + HEADER + '''
SRC = next(p.parent for p in Path("/kaggle/input").rglob("showcase.json") if (p.parent / "heldout.csv").is_file())
print("model:", SRC, flush=True)
run("scripts/export_cpu.py", "--model", str(SRC), "--validation", str(SRC / "heldout.csv"),
    "--output", "/kaggle/working/transformer-int8")
shutil.rmtree(APP, ignore_errors=True)
'''


def meta(owner, slug, gpu, sources):
    return {
        "id": f"{owner}/{slug}",
        "title": slug,
        "code_file": "kernel.py",
        "language": "python",
        "kernel_type": "script",
        "is_private": True,
        "enable_gpu": gpu,
        "enable_internet": True,
        "competition_sources": ["HerWILL-Safe-Social-Media-Datathon-2026"] if gpu else [],
        "dataset_sources": [],
        "kernel_sources": sources,
    }


# One-GPU variant: the proven single-T4 recipe only (no DDP attempt).
TRAIN_1GPU = (TRAIN[:TRAIN.index("try:\n")] + 'run(*COMMON, "--accumulation", "2")\n'
              + TRAIN[TRAIN.index('shutil.rmtree(OUT / "checkpoints"'):])
TRAIN_1GPU = TRAIN_1GPU.replace("2 T4s via DDP (batch 8 each; falls back to one T4,\n# batch 8 x 2 accumulation, if DDP crashes)",
                                "one T4, batch 8 x 2 accumulation")

blobs = {f: base64.b64encode((ROOT / f).read_bytes()).decode() for f in FILES}
FARHAN = "farhantahsinkhan"
for name, owner, template, gpu, sources, slug in [
    ("train", OWNER, TRAIN, True, [], TRAIN_SLUG),
    ("export", OWNER, EXPORT, False, [f"{OWNER}/{TRAIN_SLUG}"], EXPORT_SLUG),
    ("train-1gpu", FARHAN, TRAIN_1GPU, True, [], TRAIN_SLUG + "-1gpu"),
    ("export-1gpu", FARHAN, EXPORT, False, [f"{FARHAN}/{TRAIN_SLUG}-1gpu"], EXPORT_SLUG + "-1gpu"),
]:
    folder = HERE / name
    folder.mkdir(exist_ok=True)
    (folder / "kernel.py").write_text(template.format(blobs=blobs), encoding="utf-8")
    (folder / "kernel-metadata.json").write_text(json.dumps(meta(owner, slug, gpu, sources), indent=2) + "\n", encoding="utf-8")
    print("wrote", folder)
